name: 'Upload dSYM to Firebase Crashlytics'
description: 'Upload dSYM file to Firebase Crashlytics'
inputs:
  google-plist-content:
    description: 'Content of GoogleService-Info.plist'
    required: true
  dsym-path:
    description: 'Path to dSYM archive'
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload dSYM artifact to crashlytics
      run: |
        echo '${{ inputs.google-plist-content }}' > './.GoogleService-Info.plist'
        ./upload-symbols -gsp ./.GoogleService-Info.plist -p ios ${{ inputs.dsym-path }}
        rm ./.GoogleService-Info.plist
      shell: bash